version: '3'

services:
  django:
    image: python:3.10-buster
    container_name: contato
    restart: always
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /contato
    command: >
      bash -c "
        apt-get update &&
        pip install pip --upgrade &&
        pip install -r requirements.txt --no-cache-dir &&
        python manage.py collectstatic --no-input && 
        gunicorn --bind 0.0.0.0:8000 root.wsgi:application --timeout 900 --workers=4"
    volumes:
      - .:/contato
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    command: >
      bash -c "
        rm -f /etc/nginx/conf.d/* &&
        chown nginx:nginx /usr/share/nginx/html"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./nginx/:/etc/nginx/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email contato@meucontato.app.br -d meucontato.app.br --agree-tos

  postgresql:
    image: postgres:15.3
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql_data: