version: '3'

services:
  django:
    image: python:3.10-buster
    container_name: contato
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /contato
    command: >
      bash -c "
        apt-get update &&
        pip install pip --upgrade &&
        pip install -r requirements.txt --no-cache-dir &&
        mkdir log"
    volumes:
      - ./contato:/contato
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email contato@meucontato.app.br -d meucontato.app.br --agree-tos

  postgresql:
    image: postgres:15.3
    container_name: postgresql
    env_file:
      - ./postgresql/postgresql.env
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "3306:5432"

  volumes:
    postgresql_data: